### ISSUE TITLE
Whaaaaaaaaaaaaaaaaaaaaaat?!!!!

### ISSUE THREAD

**Issue by billiegoose** [idevelop/atom-howdoi#1]
```
laravel get database column type
```

Ctrl+?
...

``` php
DB::connection()->getDoctrineColumn('users', 'age')->getType()->getName()
```

HOLY MOTHERF*@#!!! :open_mouth: :scream: :exclamation: MIND = :boom: 

(opens README.md)

```
insert image
```

Ctrl+?
...

```
![alt tag](https://raw.githubusercontent.com/username/projectname/branch/path/to/img.png)
```

![Marty and Doc](http://aaftl.com/wp-content/uploads/2013/08/back-to-the-future-lloyd-michael-j-fox-e1380729979684.jpeg)

**Comment by idevelop** [comment]
![](http://i.imgur.com/mpvyTOY.gif)

**Comment by billiegoose** [comment]
Wait! Seriously, how is this project 2 years old yet only have 20 stars and no forks? Am I the only person who thinks this should be on the front page of Reddit (or Hacker News or whatever kids use these days)?

Is it the Google API key requirement? Because I bet we could get Google to donate one to the application. One could setup a server to cache / pre-fetch results... maybe upvote/downvote answers... the possibilities are endless. How come this is dead in the water?
